name: libproc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone polyxdr
      uses: actions/checkout@v2
      with:
        repository: polysat/polyxdr
        path: ./polyxdr
        
    - name: install
      run: cd ./polyxdr && sudo python3 setup.py install && cd ..
    
    - name: clone 
      uses: actions/checkout@v2
    
    - name: make
      run: make

