name: libproc

on: [push]

jobs:
  polyxdr:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v2
      with:
        repository: polysat/polyxdr
        path: /polyxdr
        
    - name: install
      run: python3 /polyxdr/setup.py install

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

