name: libproc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone polyxdr
      uses: actions/checkout@v2
      with:
        repository: polysat/polyxdr
        path: ./polyxdr

    - name: clone libproc
      uses: actions/checkout@v2
      with:
        path: ./libproc
      
    - name: install polyxdr
      run: cd ./polyxdr && sudo python3 setup.py install
    
    - name: make
      run: cd ./libproc && make

